on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Theory
    steps:
      - run: sudo apt-get install -y moreutils
      - uses: actions/checkout@v3
      - name: "Prepare theory files (nasty hack)"
        run: ./ci_fixer
      - name: "Isabelle Build"
        uses: lexbailey/isabelle-theory-build-github-action@v7
        with:
          isabelle-version: '2021-1'
          custom-isabelle-url: 'https://github.com/lexbailey/itrees_isabelle_fork/archive/refs/heads/itrees_utp.zip'
          depends: 'https://github.com/isabelle-utp/UTP.git@main https://github.com/isabelle-utp/UTP-Designs.git@main'
          session-name: 'Banks BanksExamples'
          doc_dir: '../documentation'
      - name: "Generate documents"
        run: ./generate_docx
      - name: "Archive documents"
        uses: actions/upload-artifact@v3
        with:
          name: "Word Documents"
          path: |
            banks.docx
            alice_guessing.docx
            localise_globalise.docx
            user_pass.docx
            user_pass_noleak.docx
